name: Build and Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install Dependencies
      run: |
        npm install
        npm install @capacitor/core @capacitor/cli @capacitor/ios @capacitor/bluetooth-le
        
    - name: Initialize Capacitor
      run: npx cap init MentalismApp io.mentalism.app --web-dir=out
        
    - name: Build Project
      run: npm run static
      
    - name: Add iOS Platform
      run: npx cap add ios
      
    - name: Sync Capacitor
      run: npx cap sync
